### ISSUE TITLE
Add Validation States for bootstrap theme

### ISSUE THREAD

**Issue by scabbiaza** [jquense/react-widgets#136]
Hello! `react-widgets` is a nice repo, guys!

I would like to ask you to add validation states for datetime picker:
http://getbootstrap.com/css/#forms-control-validation

Could you?

Something like that
```less
.form-control-validation-react-widgets(@text-color: #555; @border-color: #ccc; @background-color: #f5f5f5) {
  // Color the label and help text
  // Set the border and box shadow on specific inputs to match
  .rw-datetimepicker, .rw-select {
    border-color: @border-color;
    .box-shadow(inset 0 1px 1px rgba(0,0,0,.075)); // Redeclare so transitions work
    &:focus {
      border-color: darken(@border-color, 10%);
      @shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 6px lighten(@border-color, 20%);
      .box-shadow(@shadow);
    }
  }
}

.has-success {
  .form-control-validation-react-widgets(@state-success-text; @state-success-text; @state-success-bg);
}
.has-warning {
  .form-control-validation-react-widgets(@state-warning-text; @state-warning-text; @state-warning-bg);
}
.has-error {
  .form-control-validation-react-widgets(@state-danger-text; @state-danger-text; @state-danger-bg);
}
```
