### ISSUE TITLE
Remove blue outline 

### ISSUE THREAD

**Issue by alyssaq** [jquense/react-widgets#283]
![screen shot 2016-01-08 at 12 53 30 pm](https://cloud.githubusercontent.com/assets/2819448/12190765/8174c5cc-b607-11e5-9fa0-4f2a81672b01.png)

The following doesnt work :disappointed: 
```css
input:focus {
  outline: none;
}
```
