### ISSUE TITLE
Opening "rw-popup-container" resize container.

### ISSUE THREAD

**Issue by mattez** [jquense/react-widgets#327]
Hi.
When you create element which is using _rw-popup-container_  (DropdownList, Combobox, Multiselect,..) and set element width to 100% opening _rw-popup-container_ cause resize of container (page/form) over 100% width.

In our case we use _iframe_ to show our react-widgets form. Form is 100%, no scrollbars needed. But when you open _rw-popup-container_ horizontal scrollbars are added, because _rw-popup-container_ is overflowing.

_rw-popup-container_ is absolutely positioned, there is CSS:

```css
.rw-popup-container {
    position: absolute;
    top: 100%;
    margin-top: 1px;
    z-index: 1005;
    left: -11px;
    right: -11px;
}
```
I suggest solution in change right position form -11px to 16px>

```css
.rw-popup-container {
    position: absolute;
    top: 100%;
    margin-top: 1px;
    z-index: 1005;
    left: -11px;
    right: 16px;
}
```
It look like this (before/after):
<img width="256" alt="rw-popup-container" src="https://cloud.githubusercontent.com/assets/143115/13214653/46e1b29a-d951-11e5-956e-cc1ea7561fbc.png">

It solves problem with resizing container.
