### ISSUE TITLE
Option to disable NumberPicker's spin buttons

### ISSUE THREAD

**Issue by joshkel** [jquense/react-widgets#378]
For a project I'm working on, I'm interested in heavily changing the behavior of NumberPicker's spin buttons. (Specifically, I want to make them horizontal instead of vertical, make them focusable separately from the input element, use the Up and Down arrow keys for something else within the input element, and maybe increase the spin buttons' speed the longer they're held.)

Rather than trying to add all of that behavior to NumberPicker, it makes more sense to me to disable NumberPicker's spin buttons and manage my own button components separately. I've discovered that I can do this without modifying NumberPicker:

* Hide the spin buttons in CSS.

    ```css
    .rw-numberpicker > .rw-select { display: none; }
    ```
* Remove the space where the spin button would go in CSS, and fix the input element's corners to match the enclosing widget.

    ```css
    .rw-numberpicker { padding-right: 0; }
    .rw-numberpicker > .rw-input { border-radius: 4px; }
    ```
* Pass my own onKeyDown to disable responding to the up and down arrows:

    ```js
    onKeyDown(e) {
      if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
        e.preventDefault(); 
      }
    }
    ```

This works, but it seems ugly and brittle (especially the CSS to remove the space where the spin button would go).

Would you be open to a PR that does the following?

* Add a `hasSpinButton` prop, defaulting to true. If false, it doesn't emit the rw-select element, and it sets a CSS class so that it won't leave space for the spin button.
* If `!hasSpinButton`, don't respond to up and down arrows. (Or would it be better for `hasSpinButton` to be purely cosmetic and to continue to rely on calling `preventDefault` within `onKeyDown`?)
* Optionally, expose `NumberPicker`'s `step`, `increment`, and `decrement` methods, so that external spin buttons' `onClick` events can call them. (This isn't necessary, since I can manipulate `value` myself, but I like the consistency of continuing to use `NumberPicker`'s logic regardless of where the spin buttons are implemented.)

**Comment by jquense** [comment]
I don't think allowing the buttons to be configurable is a great option, it over complicates the component and its something I've said no to in the case of the other components. Generally I do that that handling this via css is not a bad option, and if it really doesn't suit you I'd use the underlying NumberInput component directly...it contains most of the component smarts anyway.

**Comment by joshkel** [comment]
Although I'd hoped that a single option to hide buttons would be simple enough, I understand not wanting to overcomplicate the component.

If I handle it in CSS, then I have to assume a particular implementation of the number picker - absolutely positioned buttons and `padding-right`, instead of, e.g., [Bootstrap's `input-group-addon`'s](http://getbootstrap.com/css/#forms-inline) use of `table-cell` and `float` and `:last-child`.

Is react-widgets' implementation stable enough that it's "safe" to rely on it like that? Or would I be better off using NumberInput?

(And, if I would be better off using NumberInput, would you want a PR to make it a bit more officially supported - e.g., add a docs page, probably move NumberPicker's constrainValue and max logic and some of its aria properties there, etc.?)

**Comment by markerikson** [comment]
@joshkel : Just been playing around with React-Widgets for the first time, and was having some semi-related issues wanting to reconfigure the buttons a bit.  In my case, I'm using the default RW CSS (for now - might customize it later), but want my inputs to be shorter, and have the number picker buttons be side-by-side.  I was able to add some silly override style hacks to get that working:

```css
.rw-input {
    height: 1.5em !important;
    line-height: 1.5em !important;
}

.rw-numberpicker.rw-widget {
    padding-right: 2.5em !important;
}

.rw-numberpicker .rw-select {
    width: 2.5em;
    display: flex;
    justify-content: center;
    align-items: center;
}
```

I'm not going to say this is necessarily a great idea, just trying to play with some initial visual appearance atm.  May or may not be useful for you, just wanted to throw that out there.
