### ISSUE TITLE
[4.0.0-rc.13] Multiselect vertical alignment when spanning multiple lines

### ISSUE THREAD

**Issue by huan086** [jquense/react-widgets#577]
Items in Multiselect get cut off when spanning multiple lines. Default vertical align for display:table seems to be middle, causing the cutoff. Solved by adding

```css
.rw-multiselect .rw-widget-picker > * { vertical-align: top; }
```
