### ISSUE TITLE
DatePicker IE11 styles issue

### ISSUE THREAD

**Issue by vahmur** [jquense/react-widgets#685]
Hello,
First of all i would like to thank you for a great library.
![rw-ie-bug](https://user-images.githubusercontent.com/15311809/32413640-87b3dd9a-c21e-11e7-8b89-3b608a890adb.jpg)
Looks like Datepicker styles are incorrect for IE11
Another widgets have issues too.
![rw-bug-2](https://user-images.githubusercontent.com/15311809/32414553-8d93d17a-c232-11e7-8795-1d15a0fd093a.jpg)

**Comment by lynndylanhurley** [comment]
I was able to fix this in my project by adding the following CSS to the component container class:

```scss
.container {
  :global(.rw-select) {
    position: absolute;
    overflow: hidden;
    top: 0;
    right: 0;
    width: 60px;
  }
}
```

(I'm using component local styles)
