### ISSUE TITLE
Stylus has an issue importing react-widgets.css

### ISSUE THREAD

**Issue by atomicpages** [jquense/react-widgets#907]
[Stylus chokes on filter: alpha(opacity=50) (IE hack)](https://github.com/stylus/stylus/issues/2319). I noticed that the less and the Sass files shipped with react-widgets are using this. I tried some work arounds like:

```stylus
@css {
    @import "~/react-widgets/dist/css/react-widgets.css";
}
```

but no dice.

[Less source](https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/less/mixins.less#L20) has the following:

```less
.opacity(@opacity) {
  opacity: @opacity;
  @opacity-ie: (@opacity * 100);
  filter: ~"alpha(opacity=@{opacity-ie})";
}
```

Petitioning to remove so we can import using Stylus 👍
